chore: update homepage url in package.json
koishijs/koishi-plugin-dialogue pull request #22
Opened 2023-04-11 01:41 UTC by medicago087

close #13

2023-04-11 02:59 UTC, MaikoTan approved these changes

2023-04-11 07:16 UTC, shigma requested changes
你改少了，搜一下把所有 jsorg 都换掉吧

2023-04-12 01:38 UTC, MaikoTan approved these changes

2023-04-12 05:43 UTC, shigma approved these changes

2023-04-12 05:45 UTC, merged